sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t inoumanahmed/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true inoumanahmed/frontend npm run test
